# Generated by Django 4.2.3 on 2023-08-31 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kupuvac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ime', models.CharField(blank=True, default=True, max_length=255)),
                ('Prezime', models.CharField(blank=True, default=True, max_length=255)),
                ('Username', models.CharField(blank=True, default=True, max_length=255)),
                ('godina_na_ragjane', models.IntegerField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Najava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Korisnicko_ime', models.CharField(max_length=255)),
                ('Lozinka', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prodavac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ime', models.CharField(blank=True, default=True, max_length=255)),
                ('Prezime', models.CharField(blank=True, default=True, max_length=255)),
                ('Username', models.CharField(blank=True, default=True, max_length=255)),
                ('godina_na_ragjane', models.IntegerField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proizvoditel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_na_proizvoditel', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proizvod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_na_proizvoditel', models.CharField(blank=True, default=True, max_length=255)),
                ('deskripcija', models.TextField(blank=True, default=True, max_length=2000)),
                ('zemja_na_poteklo', models.CharField(blank=True, default=True, max_length=255)),
                ('cena', models.IntegerField(blank=True, default=True)),
                ('zaliha', models.IntegerField(blank=True, default=True)),
                ('fotografija', models.ImageField(blank=True, default=True, upload_to='static/')),
                ('user', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProdavacProizvod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prodavac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cigars.prodavac')),
                ('Proizvod', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='Cigars.proizvod')),
            ],
        ),
        migrations.CreateModel(
            name='KupuvacProizvod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proizvod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cigars.proizvod')),
                ('kupuvac', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='Cigars.kupuvac')),
            ],
        ),
    ]
